# Generated by Django 6.1 on 2026-09-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=20)),
                ('school', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
